---
name: Martin
surname: Queinnec
position: "Remote Sensing Specialist | PhD"
address: "Lausanne, Switzerland (from January 2024)"
email: "martinqueinnec@gmail.com"
linkedin: "martin-queinnec"
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)

source(file = here::here("data", "data.R"))

```

```{r, include = FALSE}
source(here::here("childs/about_me.R"))
```

---
aboutme: "`r about_me`"
---

# Education

```{r Education, results = "asis"}
education %>%
  detailed_entries(
    with = Degree,
    what = Institution,
    why = Detail,
    when = Year,
    where = Where, .protect = F
  )
```

# Experience

```{r Experience, results = "asis"}
experience %>%
  detailed_entries(
    with = Position,
    what = Institution,
    why = Details,
    when = Year,
    where = Where, .protect = F
  )
```

# Skills

```{=tex}
\begin{cvskills}
  \cvskill
    {Data Science}
    {R (including spatial data processing); QGIS/ArcGIS Pro; Lidar processing (LAStools, lidR);\newline R Shiny Apps; Python; Google Earth Engine}

  \cvskill
    {Writing and Communication}
    {Microsoft Office Suite; Adobe Illustrator; Peer-reviewed publications; Teaching; Conferences}
    
  \cvskill
    {Languages}
    {English (Full proficiency); French (Native); Spanish (Intermediate)}
\end{cvskills}
```

\
\
\
\

# Awards

```{r AWARDS}
awards %>%
  detailed_entries(
    with = area,
    what = detail,
    why = accomplishment,
    when = year,
    where = where
  )
```

# Peer-reviewed publications

```{r publications}

# under_review <- bibliography_entries("../data/review_publications.bib") %>%
#   mutate(issued = "Under Review")

bib <- bibliography_entries("data/publications.bib") %>%
  arrange(desc(issued)) %>%
  mutate(issued = lubridate::as_date(issued), 
         issued = as.character(lubridate::year(issued)))
# 
# bib_all <- dplyr::bind_rows(under_review, bib)

# bib$`container-title` <- stringr::str_to_sentence(bib$`container-title`, locale = "en")

bib
```

# Conferences and workshops

```{r, Conference, results='asis'}
conferences %>%
  detailed_entries(
    with = name,
    what = desc,
    when = when,
    where = where
  )
```
